export const tracks = [
  { id: 'base', title: 'Primero, las bases', subtitle: 'Entiende qué pasa por el cable.', icon: 'layers', color: 'mint', lessons: ['fundamentos', 'ios', 'direccionamiento', 'interfaces'] },
  { id: 'switching', title: 'Conecta tu campus', subtitle: 'De una PC a toda una red.', icon: 'network', color: 'blue', lessons: ['vlans', 'trunks'] },
  { id: 'routing', title: 'Encuentra el camino', subtitle: 'Haz que las redes se hablen.', icon: 'route', color: 'purple', lessons: ['estatico', 'rip', 'ospf', 'eigrp'] },
  { id: 'services', title: 'Automatiza y protege', subtitle: 'Direcciones listas. Puertos seguros.', icon: 'shield', color: 'amber', lessons: ['dhcp', 'seguridad'] },
];

export const lessons = [
  {
    id: 'fundamentos', title: 'Lo que pasa por el cable', label: 'Fundamentos', minutes: 8, icon: 'layers',
    intro: 'Imagina que tu red es un salón: no es lo mismo hablarle a una persona que gritarle a todo el grupo.',
    takeaway: 'El switch decide con MAC dentro de una VLAN. El router decide con IP entre redes.',
    sections: [
      ['Una trama, un paquete y dos direcciones', 'La **trama Ethernet** lleva MAC origen y destino (capa 2). Dentro viaja un **paquete IP** con direcciones IP (capa 3). Un switch aprende la MAC **origen** por el puerto de entrada y consulta la MAC **destino** para reenviar. Si no la conoce, inunda los puertos de esa VLAN, excepto el de entrada.\n\nUn router consulta la red de destino en su tabla de rutas. Al cruzar un router, cambian las cabeceras de capa 2 y baja el TTL; las IP se conservan normalmente, salvo mecanismos como NAT.'],
      ['Colisión ≠ broadcast', '| Equipo | Colisiones | Broadcast |\n|---|---|---|\n| Hub | Medio compartido, un dominio | Repite a los demás puertos |\n| Switch | Separa por puerto; en full-duplex no hay colisiones | Lo limita a la VLAN |\n| Router | Separa los segmentos | No reenvía broadcasts de capa 2 entre redes |\n\n**CSMA/CD** escucha, transmite, detecta una colisión y reintenta después de un tiempo aleatorio. Aplica a Ethernet compartida/half-duplex, no a enlaces Ethernet full-duplex actuales.'],
      ['ARP, DHCP y un detalle de examen', '**ARP** pregunta por broadcast qué MAC corresponde a una IPv4 local. Si el destino está en otra red, la PC busca la MAC del **gateway**, no la MAC de la PC remota. DHCP usa difusión al iniciar el descubrimiento. **mDNS usa multicast**, no broadcast.\n\nUna VLAN constituye un dominio de broadcast. Muchos broadcasts o un bucle de capa 2 pueden saturarlo; STP ayuda a evitar bucles.'],
      ['Hardware sin confusiones', '**Ethernet:** 10 Mb/s. **FastEthernet:** 100 Mb/s. **GigabitEthernet:** 1,000 Mb/s. El modelo 2960-24TT usado habitualmente en Packet Tracer tiene 24 puertos FastEthernet y 2 Gigabit; otros 2960 tienen disposiciones distintas.\n\n**PoE / PoE+ / PoE++** se distinguen por el estándar y la potencia, no por una regla de “24, 48 y otro voltaje”. IEEE 802.3af ofrece hasta 15.4 W en el equipo que alimenta; 802.3at, 30 W; 802.3bt, hasta 60/90 W según tipo. Comprueba compatibilidad, potencia disponible, cableado y longitud.\n\nLa conexión de **consola** sirve para administrar; no sustituye un enlace Ethernet. Los módulos de fibra y las interfaces disponibles dependen del equipo seleccionado.'],
    ],
    correction: '“Un puerto = un dominio de colisión” es la regla didáctica; en full-duplex no hay colisiones ni se usa CSMA/CD.',
    sources: ['Clases/Dominio de colision y de broadcast.md', 'Clases/Dominio de Broadcast.md', 'Clases/Comparativa Colision vs Broadcast.md', 'Clases/CSMA CD.md', 'VLANS/Clases/9 julio.md'],
  },
  {
    id: 'ios', title: 'Habla el idioma del switch', label: 'Cisco IOS', minutes: 10, icon: 'terminal',
    intro: 'El prompt es tu ubicación. Antes de memorizar un comando, aprende en qué “habitación” se escribe.',
    takeaway: '> usuario · # privilegiado · (config)# configuración · (config-if)# interfaz.',
    sections: [
      ['Tu mapa de modos', '| Prompt | Modo | Cómo llegar |\n|---|---|---|\n| Switch> | EXEC usuario | Al abrir consola |\n| Switch# | EXEC privilegiado | enable |\n| Switch(config)# | Configuración global | configure terminal |\n| Switch(config-if)# | Interfaz | interface fa0/1 |\n| Switch(config-vlan)# | VLAN | vlan 101 |\n| Switch(config-line)# | Línea | line console 0 |\n\n`exit` sube un nivel. `end` o Ctrl+Z regresan a privilegiado desde configuración. `?` muestra ayuda contextual. Las abreviaturas funcionan cuando no son ambiguas.'],
      ['Configuración inicial de la clase', 'Ejemplo para un equipo de laboratorio. `12345` reproduce la contraseña didáctica de los apuntes; no es una recomendación para equipos reales.\n\n```cisco\nenable\nconfigure terminal\nhostname SW-BRAULIO\nenable secret 12345\nline console 0\n password 12345\n login\nexit\nline vty 0 15\n password 12345\n login\nexit\nservice password-encryption\nbanner motd #ACCESO SOLO AUTORIZADO#\nend\nwrite memory\n```\n\nLa cantidad de líneas VTY depende del modelo/IOS. Si `0 15` no existe, consulta `line vty ?`. La configuración de VTY de la clase no habilita por sí sola SSH.'],
      ['Guardar y comprobar', '`running-config` es la configuración activa en RAM. `startup-config` se usa al arrancar.\n\n```cisco\nshow running-config\nshow startup-config\ncopy running-config startup-config\n```\n\n`write memory` (o `wr`) guarda la configuración. Desde `(config)#`, vuelve con `end` antes de usar los comandos de verificación; IOS también admite muchos comandos EXEC con `do`.'],
      ['Qué sí hace cada contraseña', '`enable secret` protege el acceso privilegiado. `password` + `login` piden una contraseña en la línea. En IOS clásico, `service password-encryption` ofusca contraseñas de línea con tipo 7, que es reversible: **no cifra la sesión de red**. Para administración remota real se prefiere SSH con usuarios locales o AAA.'],
    ],
    correction: 'Si “ip dhcp excluded-address” falla en CORE#, entra primero a configure terminal. El modo también forma parte del comando.',
    sources: ['CONFIGURACION BASICA.md', 'Configuraciones/Configuracion Basica.md', 'Configuraciones/Resumen.md', 'Clases/Configuracion Router 25.md', 'Clases/Configuracion Router 26 de Junio.md'],
  },
  {
    id: 'direccionamiento', title: 'IP, máscara y gateway sin enredos', label: 'Direccionamiento', minutes: 12, icon: 'calculator',
    intro: 'La IP es tu domicilio, la máscara define tu colonia y el gateway es la salida a las demás colonias.',
    takeaway: 'En 192.168.1.4/30: red .4, hosts .5 y .6, broadcast .7.',
    sections: [
      ['Las tres piezas de una PC', '| Dato | Ejemplo | Para qué sirve |\n|---|---|---|\n| IPv4 | 10.168.101.11 | Identificar al host |\n| Máscara | 255.255.255.0 (/24) | Saber si el destino está en su subred |\n| Gateway | 10.168.101.1 | Enviar paquetes hacia otras redes |\n| DNS | 8.8.8.8 | Resolver nombres |\n\nDos PCs en la misma VLAN y subred pueden comunicarse sin gateway. Para otras redes necesitan uno alcanzable en su subred. La PC y el gateway **no deben repetir IP**. Configurar DNS no crea acceso a Internet.'],
      ['La máscara y su inversa', '| Prefijo | Máscara | Wildcard | Hosts convencionales |\n|---|---|---|---|\n| /24 | 255.255.255.0 | 0.0.0.255 | 254 |\n| /26 | 255.255.255.192 | 0.0.0.63 | 62 |\n| /30 | 255.255.255.252 | 0.0.0.3 | 2 |\n\nLa **wildcard** usada aquí se obtiene restando cada octeto de la máscara a 255. En OSPF selecciona las interfaces cuya IP coincide; no se configura como máscara de una interfaz.\n\nEn una subred convencional: total = 2^(32 − prefijo), hosts = total − 2. /31 es una excepción para enlaces punto a punto; /32 representa un host.'],
      ['Aprende a saltar de cuatro en cuatro', 'Las redes /30 avanzan `.0`, `.4`, `.8`, `.12`… Por eso `192.168.1.4/30` contiene `.4` a `.7`. No configures la dirección de red ni la de broadcast en una interfaz. Usa la **calculadora de subredes** en el mapa para comprobar cualquier IPv4/prefijo.'],
      ['¿Qué direcciones son privadas?', 'RFC 1918 reserva **10.0.0.0/8**, **172.16.0.0/12** (172.16 a 172.31) y **192.168.0.0/16**.\n\n**172.32.x.x no es privada**. Los apuntes de routing y el simulador Cisco usan también rangos públicos como 7.0.0.0 o 200.1.2.0. Aquí se mantienen para reproducir esos ejercicios aislados; el campus nuevo usa 10.168.x.x.'],
    ],
    correction: '255.255.255.8 no es una máscara de subred contigua válida. En las LAN /24 de la práctica corresponde 255.255.255.0.',
    sources: ['Configuraciones/Practica RIP.md', 'Configuraciones/Protocolo EIGRP.md', 'Clases/Clase 29 de Junio Algo de router.md'],
  },
  {
    id: 'interfaces', title: 'Dale vida a las interfaces', label: 'Interfaces y pruebas', minutes: 9, icon: 'plug',
    intro: 'Antes de culpar a RIP u OSPF, comprueba el cable, la IP y el estado del puerto.',
    takeaway: 'En un router: interface → ip address → no shutdown. Después, show ip interface brief.',
    sections: [
      ['La receta en un router', '```cisco\nenable\nconfigure terminal\ninterface gigabitEthernet0/0\n ip address 192.168.0.1 255.255.255.0\n no shutdown\nexit\nend\nshow ip interface brief\n```\n\nConfigura la PC como `192.168.0.2/24`, gateway `192.168.0.1`. Los nombres de interfaces cambian según el modelo: usa `show ip interface brief` para identificarlos. En un puerto físico de switch capa 2 no asignas esta IP; usas una **SVI** de administración.'],
      ['Serial y clock rate', 'Para los routers 1941 de la práctica, apaga el equipo en Packet Tracer antes de agregar un módulo serial. Usa el puerto que corresponda a tu cableado.\n\n```cisco\nshow controllers serial0/0/0\n```\n\nSi tu extremo es **DCE** y debe proporcionar reloj, configura `clock rate 64000` dentro de esa interfaz. El extremo DTE recibe reloj. No se usa `clock rate` en una GigabitEthernet hacia una PC.'],
      ['Lee los dos estados', '| Estado | Qué revisar |\n|---|---|\n| administratively down / down | Falta no shutdown |\n| down / down | Cable, equipo remoto, módulo o puerto |\n| up / down | Protocolo de enlace, encapsulación, reloj en serial o condiciones de SVI |\n| up / up | Capas física y de enlace operativas; todavía puede fallar IP/routing |\n\n`unassigned` en un puerto físico L2 es normal. En la SVI que debería administrar el switch, sí indica que falta IP.'],
      ['Prueba de cerca hacia lejos', '1. Verifica la IP y la máscara de tu PC.\n2. Haz ping al gateway.\n3. Haz ping al vecino del router.\n4. Revisa `show ip route`.\n5. Haz ping al host remoto y comprueba la ruta de regreso.\n\nEl primer ping puede perder un paquete mientras se resuelve ARP. Un ping exitoso confirma esa conectividad, no demuestra que toda la configuración esté perfecta.'],
    ],
    correction: '“up/up” no garantiza que exista una ruta al destino. Y “unassigned” no significa automáticamente que el puerto esté mal.',
    sources: ['Configuraciones/Configuracion de interfaces.md', 'Configuraciones/Practica RIP.md', 'VLANS/Practica9/Si sale unassigned.md', 'VLANS/Practica9/Compronacion.md'],
  },
  {
    id: 'vlans', title: 'Un switch, varios mundos', label: 'VLAN y access', minutes: 10, icon: 'network',
    intro: 'Sistemas y Electrónica pueden usar el mismo switch sin compartir su dominio de broadcast.',
    takeaway: 'Crear una VLAN no asigna los puertos: necesitas vlan + switchport access vlan.',
    sections: [
      ['Piensa en salones separados', 'Una **VLAN** es una separación lógica de capa 2. Cada VLAN tiene su propio dominio de broadcast. En estos ejercicios se asigna una subred IPv4 por VLAN.\n\nUn puerto **access** transporta una VLAN de datos y normalmente entrega tramas sin etiqueta a una PC. Un enlace **trunk** permite transportar varias VLAN con 802.1Q. Un teléfono IP puede usar además una voice VLAN; es un caso distinto al access de datos simple.'],
      ['Crear y asignar', '```cisco\nenable\nconfigure terminal\nvlan 101\n name SISTEMAS\nexit\ninterface range fastEthernet0/1 - 16\n switchport mode access\n switchport access vlan 101\n no shutdown\nexit\nend\nshow vlan brief\nwrite memory\n```\n\nDebes ver VLAN 101 activa con Fa0/1 a Fa0/16. El nombre es una etiqueta; la identidad de la VLAN es el **número**. Crearla en el CORE no la crea automáticamente en todos los switches: aquí se configura en cada equipo.'],
      ['Las VLAN de tu verano', '| VLAN | Uso |\n|---|---|\n| 23 | VOZ |\n| 100 | ADMINISTRATIVA: 10.168.0.0/24 |\n| 101–110 | Sistemas, Electrónica, CEA, Dirección, Escolares, Civil, Química, Industrial, Contabilidad, Eléctrica |\n| 301 | AP-ADMON |\n| 302 | INALAMBRICA |\n\nEn los switches de enlace: **Fa0/1–16** para el departamento, **Fa0/17–18** para VLAN 23, **Fa0/19** para VLAN 301, **Fa0/24** para VLAN 100. Los apuntes no asignan puertos finales a la VLAN 302.'],
      ['Cambiar o eliminar sin empezar de cero', 'Para cambiar Fa0/1 a otra VLAN existente, entra a la interfaz y usa `switchport access vlan 102`.\n\n`no vlan 101` elimina la VLAN desde configuración global; los puertos asignados pueden quedar inactivos hasta reasignarlos. `default interface fa0/1` reinicia la configuración de ese puerto.\n\n`vlan 100` crea/edita la VLAN L2. `interface vlan 100` crea/edita su **SVI**; no sustituye asignar puertos ni nombrar la VLAN.'],
    ],
    correction: 'La práctica del simulador Cisco usa Sistemas 110 e Industrial 116. En la práctica de verano son 101 y 108. Son escenarios diferentes.',
    sources: ['VLANS/Clases/Intro.md', 'VLANS/Clases/VLANS.md', 'VLANS/Practica9/CREACION DE VLANS SWITCH PRINCIPAL.md', 'VLANS/Practica9/Codigos Terminados Acces.md', 'VLANS/Practica9/No te salen los nombres en enlace.md'],
  },
  {
    id: 'trunks', title: 'El puente entre tus VLANs', label: 'Trunk, SVI y CORE', minutes: 12, icon: 'route',
    intro: 'Un trunk es una carretera con carriles separados. El equipo de capa 3 es el que permite cambiar de una red a otra.',
    takeaway: 'Trunk transporta VLANs. SVI + ip routing en un switch multicapa permite enrutarlas.',
    sections: [
      ['Trunk en ambos extremos', 'Ejemplo del enlace de Sistemas, en cada extremo del cable:\n\n```cisco\nenable\nconfigure terminal\ninterface gigabitEthernet0/1\n switchport mode trunk\n switchport trunk native vlan 1\n switchport trunk allowed vlan 23,100,101,301,302\n no shutdown\nexit\nend\nshow interfaces trunk\n```\n\nComprueba que ambas puntas coincidan en VLAN nativa y permitan las VLAN necesarias. En 802.1Q, la VLAN nativa normalmente sale sin etiqueta; la VLAN de administración **no se vuelve nativa** por tener una IP. Este escenario mantiene nativa 1, como valor por defecto, y administración 100 etiquetada.\n\n`switchport trunk allowed vlan 101` **reemplaza** la lista; para agregar sin quitar otras, usa `switchport trunk allowed vlan add 101`.'],
      ['Administrar un switch de capa 2', '```cisco\nenable\nconfigure terminal\nvlan 100\n name ADMINISTRATIVA\nexit\ninterface vlan 100\n ip address 10.168.0.3 255.255.255.0\n no shutdown\nexit\nip default-gateway 10.168.0.1\nend\n```\n\nLa SVI necesita la VLAN creada y activa, y al menos un puerto de esa VLAN operativo en forwarding (puede ser un trunk que la transporte). `no shutdown` por sí solo no garantiza `up/up`.\n\n`ip default-gateway` sirve para el tráfico de administración del switch **cuando no está enrutando**; no configura el gateway de las PCs.'],
      ['Comunicar VLAN 101 con VLAN 102', 'Para esta versión reproducible del laboratorio, usa un **switch multicapa compatible** (por ejemplo, 3560 en Packet Tracer), crea ambas VLAN, configura sus enlaces y habilita routing:\n\n```cisco\nenable\nconfigure terminal\nip routing\ninterface vlan 101\n ip address 10.168.101.1 255.255.255.0\n no shutdown\nexit\ninterface vlan 102\n ip address 10.168.102.1 255.255.255.0\n no shutdown\nexit\nend\nshow ip route\n```\n\nLas PCs usan su respectiva `.1` como gateway. Otra solución es router-on-a-stick con subinterfaces 802.1Q. Un 2960 L2 básico o un PT-EMPTY sin esas capacidades no debe suponerse capaz de hacer este trabajo.'],
      ['Reconstruye una rama antes de ampliar', 'La jerarquía es **CORE → distribución → enlace → PC**. El generador del mapa reconstruye una rama por departamento, con Gi0/1 como uplink y Gi0/2 como downlink de distribución. Los apuntes usan módulos con nombres como Gi1/1: adapta los puertos al equipo real.\n\nEl bloque CORE es por rama: al ampliar a diez departamentos, cada rama necesita su puerto físico propio y su lista de VLAN. No pegues todos los bloques en Gi0/1, porque sobrescribirías su lista.'],
    ],
    correction: 'Poner IP en VLAN 100 permite administrar el switch. Para enrutar las VLAN de usuarios hacen falta capacidades L3, gateways por VLAN e ip routing.',
    sources: ['VLANS/Practica9/Que es trunk y access.md', 'VLANS/Practica9/Configurar Puerto trunk e IP.md', 'VLANS/Practica9/Modo truck y ip en cada uno.md', 'VLANS/Practica9/Configuracion Gateway.md', 'VLANS/Practica9/SWITCH CORE.md'],
  },
  {
    id: 'estatico', title: 'Dile al router por dónde ir', label: 'Rutas estáticas', minutes: 10, icon: 'route',
    intro: '“Para llegar a esa red, entrégale el paquete a este vecino”. Esa es toda la idea de una ruta estática.',
    takeaway: 'ip route RED_DESTINO MÁSCARA SIGUIENTE_SALTO. Recuerda la ruta de regreso.',
    sections: [
      ['La ruta se escribe hacia lo remoto', 'Las redes directamente conectadas aparecen como **C** cuando la interfaz está operativa; la dirección propia de interfaz suele aparecer como **L /32**. Para una red remota, configura el siguiente salto alcanzable:\n\n```cisco\nenable\nconfigure terminal\nip route 192.168.4.0 255.255.255.0 209.168.130.66\nend\nshow ip route\n```\n\nEn R1 significa: “para 192.168.4.0/24, entrega al vecino 209.168.130.66”. La ruta estática instalada aparece con **S**. No uses la IP de tu propia interfaz como siguiente salto.'],
      ['Ida y vuelta', 'En la práctica, R1 y R2 comparten `209.168.130.64/30`: R1 `.65`, R2 `.66`. R2 y R3 comparten `185.145.127.0/30`: R2 `.1`, R3 `.2`.\n\nR1 necesita caminos hacia las LAN de R2/R3. R3 necesita caminos hacia las LAN de R1/R2. R2 necesita rutas hacia ambos extremos. Un ping puede fallar si solo configuraste la ida.'],
      ['Por defecto, flotante y selección', '`ip route 0.0.0.0 0.0.0.0 SIGUIENTE_SALTO` es la ruta por defecto: se utiliza cuando no existe una coincidencia más específica. Una ruta estática flotante tiene una **distancia administrativa mayor** que la principal al mismo prefijo, por ejemplo `... 200`.\n\nPrimero se prefiere la coincidencia de prefijo más larga para reenviar. Para instalar rutas al mismo prefijo de fuentes distintas se compara distancia administrativa; dentro del protocolo, su métrica. La estática normal tiene AD 1.\n\nUna ruta flotante depende de que desaparezca la principal de la tabla; para detectar algunos fallos remotos se necesita seguimiento adicional.'],
      ['Cuándo te conviene', 'Es útil en redes pequeñas, salidas únicas y rutas de respaldo. El operador mantiene los cambios manualmente. **No tiene un límite universal de 15 saltos**: ese límite pertenece a RIP. La elección entre estático y dinámico no determina por sí sola que una red sea segura.'],
    ],
    correction: 'El comando es ip route, no ip router. La máscara es la del destino, no la del enlace al vecino.',
    sources: ['Configuraciones/Protocolo  Estatico.md', 'Clases/Clase 29 de Junio Algo de router.md', 'Clases/Clase 30 Junio.md'],
  },
  {
    id: 'rip', title: 'Los vecinos se pasan el mapa', label: 'RIPv2', minutes: 11, icon: 'route',
    intro: 'En lugar de escribir cada destino lejano, activa RIP en tus redes conectadas y deja que los routers compartan rutas.',
    takeaway: 'RIPv2 usa saltos: 15 como máximo alcanzable; 16 significa infinito.',
    sections: [
      ['Qué decide RIP', 'RIP es un protocolo interior de **vector distancia**. Su métrica es la cantidad de saltos, no el ancho de banda. Envía actualizaciones periódicas aproximadamente cada 30 segundos y también puede enviar actualizaciones disparadas por cambios. RIPv2 transporta máscaras y admite VLSM.\n\nLa AD por defecto en Cisco es **120**; las rutas aparecen con **R**. La convergencia es relativamente lenta y se utiliza aquí con fines didácticos.'],
      ['Configurar R1 de los apuntes', '```cisco\nenable\nconfigure terminal\nrouter rip\n version 2\n network 7.0.0.0\n network 8.0.0.0\n network 192.168.1.0\n no auto-summary\nend\nwrite memory\nshow ip protocols\nshow ip route rip\n```\n\nEn IOS, `network` en RIP selecciona interfaces según su **red mayor classful**, sin wildcard. `network 192.168.1.0` cubre las seriales /30 dentro de esa red mayor. RIPv2 sigue anunciando las subredes con sus máscaras; `no auto-summary` desactiva el resumen automático en fronteras classful.'],
      ['Cuatro routers, ocho LAN', 'R1 tiene las LAN 7 y 8; R2, 9 y 10; R3, 11 y 12; R4, 13 y 14, todas /24. Los enlaces seriales usan `192.168.1.0/30`, `.4/30`, `.8/30` y `.12/30`.\n\nEn cada router activa RIP en sus dos redes LAN y en `192.168.1.0`. No escribas como `network` las LAN remotas esperando que se cree una ruta estática. Puedes usar `passive-interface` en las interfaces LAN hacia PCs para no enviar actualizaciones allí y seguir anunciando esas redes.'],
      ['Verifica antes del ping final', 'Busca RIPv2 y ausencia de auto-summary en `show ip protocols`. Comprueba rutas remotas con **R** y que las interfaces estén `up/up`.\n\nUn registro `[120/2]` significa AD 120 y métrica 2 saltos. Que existan rutas R no garantiza todos los destinos; revisa específicamente la red que quieres alcanzar y su regreso.'],
    ],
    correction: 'No confundas “red conectada” con escribir la IP del host o cada /30 literalmente: network en RIP IOS opera sobre redes mayores classful.',
    sources: ['Configuraciones/Protocolo RIP.md', 'Configuraciones/Practica RIP.md', 'Clases/Clase 30 Junio.md'],
  },
  {
    id: 'ospf', title: 'Cada router conoce el mapa', label: 'OSPF', minutes: 12, icon: 'compass',
    intro: 'OSPF comparte el estado de los enlaces y calcula caminos de menor costo. Piensa en un mapa, no solo en contar calles.',
    takeaway: 'Área 0 = backbone. Process ID local; router ID único. La wildcard selecciona interfaces.',
    sections: [
      ['Estado de enlace y costo', 'OSPF es un IGP de **estado de enlace** que utiliza SPF (Dijkstra). Su métrica es el **costo acumulado**. En IOS, el costo automático parte del ancho de banda de referencia dividido entre el ancho de banda de la interfaz, con mínimo 1. La referencia tradicional es 100 Mb/s; conviene ajustarla consistentemente si necesitas distinguir enlaces más rápidos.\n\nOSPF no mide por sí mismo la congestión instantánea para escoger una ruta. Su AD por defecto es **110**.'],
      ['Área 0 y las identidades', 'El **área 0 es el backbone**, no un área “no backbone”. En un diseño multiárea, las demás áreas deben tener conectividad con él. Esta práctica usa solo área 0.\n\n`router ospf 1`: el 1 es un **process ID local**, no necesita coincidir entre vecinos. `router-id 0.0.0.1`: identifica al router y debe ser único en el dominio OSPF. No necesita ser una IP configurada en una interfaz.'],
      ['R1 de la práctica de cuatro routers', '```cisco\nenable\nconfigure terminal\nrouter ospf 1\n router-id 0.0.0.1\n network 192.168.1.0 0.0.0.255 area 0\n network 172.16.0.0 0.0.0.255 area 0\n network 192.168.3.0 0.0.0.3 area 0\n network 200.1.0.0 0.0.0.3 area 0\nend\nshow ip ospf neighbor\nshow ip route ospf\n```\n\n`network` no fabrica una ruta a cualquier red: **activa OSPF sobre las interfaces que coinciden con IP + wildcard**, asignándolas al área. Las subredes de esas interfaces se anuncian según su máscara real.'],
      ['Vecinos y diagnóstico', 'Comprueba área, subred, temporizadores Hello/Dead, autenticación y tipo de red compatibles. MTU distinta puede impedir completar una adyacencia. Usa:\n\n```cisco\nshow ip ospf neighbor\nshow ip ospf interface\nshow ip ospf database\nshow ip route ospf\n```\n\n**FULL** indica una adyacencia completa. En redes multiacceso, dos DROTHER pueden permanecer legítimamente en **2-WAY** entre sí; no toda vecindad debe llegar a FULL. Las rutas intraárea se marcan **O**; también existen O IA y externas.'],
    ],
    correction: 'El área 0 sí es backbone. OSPF elige por costo, no por menos saltos ni por medir la congestión en tiempo real.',
    sources: ['Configuraciones/Protocolo OSPF.md', 'Configuraciones/Configuración del protocolo OSPF.md'],
  },
  {
    id: 'eigrp', title: 'Un vistazo a EIGRP', label: 'EIGRP · complemento', minutes: 7, icon: 'compass',
    intro: 'Tus apuntes solo introducen EIGRP y las wildcards. Esta explicación amplía esa base para que no quede un tema suelto.',
    takeaway: 'EIGRP es vector distancia avanzado, usa DUAL y por defecto combina ancho de banda y retardo.',
    sections: [
      ['Lo esencial', 'EIGRP usa el algoritmo **DUAL**. Mantiene vecinos y puede disponer de un sucesor factible como respaldo libre de bucles. Con valores K clásicos por defecto, su métrica combina el **menor ancho de banda** del camino y la **suma de retardos**. No es una métrica simple de saltos.\n\nEn Cisco: AD **90** para rutas internas y **170** para externas. El código de ruta es **D**.'],
      ['Ejemplo complementario de dos routers', 'Con LAN 192.168.10.0/24 en R1 y un enlace 10.0.0.0/30 a R2:\n\n```cisco\nenable\nconfigure terminal\nrouter eigrp 100\n network 192.168.10.0 0.0.0.255\n network 10.0.0.0 0.0.0.3\n no auto-summary\n passive-interface gigabitEthernet0/0\nend\nshow ip eigrp neighbors\nshow ip route eigrp\n```\n\nSe supone que Gi0/0 es la LAN. En modo clásico, vecinos deben usar el mismo **AS 100**, parámetros compatibles y conectividad IP. En R2 anuncia su propia LAN y el enlace compartido; no la LAN de R1 como si fuera local.'],
      ['No mezcles las identidades', 'El número de `router eigrp 100` debe coincidir entre vecinos de esta configuración clásica. El de `router ospf 1` es local. Es una diferencia típica de examen.\n\nEl ejemplo es una ampliación didáctica, no una práctica completa encontrada en los apuntes. La sintaxis y funciones disponibles dependen del IOS y del modelo.'],
    ],
    correction: 'La nota original era incompleta. Esta sección está identificada como complemento, no como transcripción de una práctica realizada.',
    sources: ['Configuraciones/Protocolo EIGRP.md'],
  },
  {
    id: 'dhcp', title: 'Una IP, sin escribirla a mano', label: 'DHCP y DORA', minutes: 10, icon: 'zap',
    intro: 'La PC pregunta, el servidor ofrece, la PC solicita y el servidor confirma. DORA: cuatro pasos que sí se quedan.',
    takeaway: 'Discover → Offer → Request → ACK. Excluye las IP fijas antes de repartir el pool.',
    sections: [
      ['DORA, en palabras de tu PC', '1. **Discover:** “¿Hay algún servidor DHCP?” El cliente inicia por broadcast.\n2. **Offer:** “Te ofrezco esta IP y estos parámetros.”\n3. **Request:** “Solicito esa oferta.” En la selección inicial informa por broadcast.\n4. **ACK:** “Confirmado, puedes usarla durante este arrendamiento.”\n\nDHCPv4 usa UDP **67** en el servidor y **68** en el cliente. Las ofertas/respuestas pueden ser unicast o broadcast según estado y condiciones. Las renovaciones no repiten necesariamente los cuatro pasos iniciales.'],
      ['El pool de Sistemas', 'El CORE del ejercicio debe admitir DHCP servidor y tener VLAN 101, su SVI `10.168.101.1/24` operativa y los trunks/access correctos.\n\n```cisco\nenable\nconfigure terminal\nip dhcp excluded-address 10.168.101.1 10.168.101.10\nip dhcp pool SISTEMAS\n network 10.168.101.0 255.255.255.0\n default-router 10.168.101.1\n dns-server 8.8.8.8\nexit\nend\nshow ip dhcp pool\nshow ip dhcp binding\n```\n\nQuedan disponibles `.11` a `.254`; no prometas que la primera concesión será siempre `.11`, porque puede haber concesiones o conflictos previos. La red `.0` y broadcast `.255` no son IP de host.'],
      ['¿Tiene que estar en el CORE?', '**Solo en esta topología** se eligió ubicar DHCP ahí. También puede ejecutarse en un router o servidor dedicado. Si el servidor está en otra subred, configura un **relay** en la interfaz L3 del cliente con `ip helper-address IP_DEL_SERVIDOR` y asegura rutas de ida y vuelta.\n\nDHCP asigna parámetros; **NAT traduce direcciones** (y PAT puede traducir puertos). Son funciones independientes.'],
      ['Si aparece 169.254…', 'Algunos sistemas, como Windows, se autoasignan una IPv4 **link-local/APIPA** si no obtienen una concesión. El bloque es `169.254.0.0/16`; la selección dinámica de RFC 3927 usa `169.254.1.0` a `169.254.254.255`. Estas direcciones no se enrutan fuera del enlace.\n\nRevisa en orden: enlace → VLAN access → trunk → SVI → pool/exclusiones → relay si aplica. No concluyas “el servidor está roto” solo porque la PC no recibe IP.'],
    ],
    correction: 'Para 10.168.101.0/24, el gateway del ejemplo es 10.168.101.1, no 10.168.1.10. DHCP no necesita estar siempre en el CORE.',
    sources: ['Protocolo DHCP.md', 'Configuracion DHCP 10 julio.md'],
  },
  {
    id: 'seguridad', title: 'Este puerto ya tiene dueño', label: 'Port Security', minutes: 10, icon: 'shield',
    intro: 'Fa0/1 conoce la MAC de tu PC. Si conectas otra y solo se permite una, el switch reacciona.',
    takeaway: 'Sticky aprende una MAC en running-config. Guarda después de aprenderla para conservarla al reiniciar.',
    sections: [
      ['Protege el puerto de la PC', 'En el switch de enlace de Sistemas, con VLAN 101 ya creada:\n\n```cisco\nenable\nconfigure terminal\ninterface fastEthernet0/1\n switchport mode access\n switchport access vlan 101\n switchport port-security\n switchport port-security maximum 1\n switchport port-security mac-address sticky\n switchport port-security violation shutdown\n no shutdown\nexit\nend\n```\n\nGenera tráfico desde la PC autorizada (por ejemplo, ping a `10.168.101.1`), verifica la MAC y **después guarda** con `write memory`. La práctica protege Fa0/1, no el trunk de subida.'],
      ['Tres formas de reaccionar', '| Modo | Tráfico de MAC no permitida | Registro/contador | Puerto |\n|---|---|---|---|\n| protect | Descarta | Sin notificación de violación | Sigue activo |\n| restrict | Descarta | Incrementa contador y puede notificar | Sigue activo |\n| shutdown | Bloquea el puerto | Registra violación | err-disabled |\n\nPort Security filtra por MAC; no autentica criptográficamente a una persona ni impide que una MAC sea suplantada.'],
      ['Provoca y observa la violación', 'Desconecta la PC autorizada, conecta otra al **mismo Fa0/1** y genera tráfico. Después revisa:\n\n```cisco\nshow port-security interface fa0/1\nshow port-security address\nshow interfaces fa0/1\n```\n\nBusca `Secure-shutdown`, un contador de violaciones mayor que cero y `err-disabled`. “DHCP request failed” por sí solo no demuestra Port Security: estas salidas sí te permiten identificar la causa.'],
      ['Recupera el puerto con intención', 'Retira primero el dispositivo no autorizado y reconecta la PC original.\n\n```cisco\nenable\nconfigure terminal\ninterface fastEthernet0/1\n shutdown\n no shutdown\nend\nshow port-security interface fa0/1\n```\n\nSi la MAC sticky aprendida era equivocada, inspecciona `show running-config` y elimina la **entrada concreta** dentro de la interfaz con `no switchport port-security mac-address sticky XXXX.XXXX.XXXX`, usando la MAC real que aparece. Luego aprende la autorizada y vuelve a guardar. No asumas que desactivar/reactivar sticky limpia todas las direcciones en cualquier IOS.'],
    ],
    correction: 'Guardar antes de aprender la MAC no guarda una MAC que todavía no existe. Genera tráfico, comprueba la entrada y guarda otra vez.',
    sources: ['Configuracion de port security.md', 'Resumen de la actividad port securyti.md'],
  },
];

export const references = [
  ['RFC 1918', 'Rangos IPv4 privados', 'https://www.rfc-editor.org/rfc/rfc1918#section-3'],
  ['RFC 2131', 'DHCP y asignación inicial', 'https://www.rfc-editor.org/rfc/rfc2131'],
  ['RFC 2328', 'OSPFv2, backbone y adyacencias', 'https://www.rfc-editor.org/rfc/rfc2328'],
  ['RFC 2453', 'RIPv2 y límite de saltos', 'https://www.rfc-editor.org/rfc/rfc2453'],
  ['RFC 3927', 'IPv4 link-local / APIPA', 'https://www.rfc-editor.org/rfc/rfc3927#section-2.1'],
  ['RFC 3021', 'Prefijos /31 punto a punto', 'https://www.rfc-editor.org/rfc/rfc3021'],
  ['RFC 7868', 'Descripción de EIGRP (informativo)', 'https://www.rfc-editor.org/rfc/rfc7868'],
  ['Cisco 2960', 'Documentación de configuración por versión', 'https://www.cisco.com/c/en/us/support/switches/catalyst-2960-series-switches/products-installation-and-configuration-guides-list.html'],
];

export const questions = [
  ['fundamentos', '¿Qué dirección aprende un switch al recibir una trama?', ['MAC origen', 'MAC destino', 'IP de DNS', 'IP pública'], 0, 'Aprende la MAC origen y la asocia al puerto de entrada. Después busca la MAC destino para reenviar.'],
  ['fundamentos', '¿Dónde se usa CSMA/CD?', ['En todo enlace full-duplex', 'En Ethernet compartida/half-duplex', 'Solo en OSPF', 'En DHCP'], 1, 'En full-duplex no hay colisiones; CSMA/CD pertenece al medio Ethernet compartido/half-duplex.'],
  ['ios', 'Estás en Switch>. ¿Qué comando te lleva a Switch#?', ['configure terminal', 'interface vlan 1', 'enable', 'write memory'], 2, 'enable entra al EXEC privilegiado. Después configure terminal entra a configuración global.'],
  ['ios', '¿Qué hace service password-encryption en el IOS clásico de la práctica?', ['Habilita SSH', 'Cifra todo el tráfico', 'Genera un certificado', 'Ofusca contraseñas de línea con tipo 7'], 3, 'El tipo 7 es reversible. No cifra la sesión y no sustituye SSH.'],
  ['direccionamiento', '¿Cuáles son los hosts de 192.168.1.4/30?', ['.4 y .5', '.5 y .6', '.6 y .7', '.1 y .2'], 1, 'El bloque va de .4 a .7: red .4, hosts .5/.6 y broadcast .7.'],
  ['direccionamiento', '¿Cuál de estas direcciones NO pertenece a RFC 1918?', ['10.168.1.1', '172.16.1.1', '172.32.1.1', '192.168.1.1'], 2, 'El rango privado 172 abarca 172.16 hasta 172.31, no 172.32.'],
  ['interfaces', '¿Qué sugiere administratively down?', ['Falta no shutdown', 'Hay demasiadas VLAN', 'La máscara es /24', 'DNS no responde'], 0, 'La interfaz está deshabilitada administrativamente. Entra a esa interfaz y usa no shutdown.'],
  ['interfaces', '¿Dónde configuras clock rate en el laboratorio serial?', ['En toda Gigabit', 'En las PCs', 'En ambos extremos siempre', 'En el extremo DCE que proporciona reloj'], 3, 'El DCE proporciona reloj; compruébalo con show controllers serial. El DTE lo recibe.'],
  ['vlans', 'Creaste VLAN 101, pero Fa0/1 sigue en VLAN 1. ¿Qué falta?', ['Cambiar el DNS', 'switchport access vlan 101 en Fa0/1', 'router rip', 'Borrar startup-config'], 1, 'Crear una VLAN no cambia automáticamente la pertenencia de los puertos. Configura el puerto correcto en modo access.'],
  ['vlans', '¿Cuántos dominios de broadcast representan tres VLAN distintas?', ['Uno', 'Dos', 'Tres', 'Uno por puerto físico'], 2, 'Cada VLAN constituye un dominio de broadcast, aunque se extienda por varios switches mediante trunks.'],
  ['trunks', '¿Un trunk permite por sí solo comunicar dos VLAN distintas?', ['Sí, siempre', 'Solo si es Gigabit', 'Solo con VLAN nativa 1', 'No; hace falta enrutamiento inter-VLAN'], 3, 'El trunk transporta VLANs separadas. Un router o switch multicapa con gateways adecuados permite comunicarlas.'],
  ['trunks', '¿Qué hace switchport trunk allowed vlan 101 sin add?', ['Reemplaza la lista permitida por 101', 'Agrega 101 conservando todas', 'Crea VLAN 101 en todos los switches', 'Hace nativa la VLAN 101'], 0, 'Sin add, se reemplaza la lista. Usa allowed vlan add 101 para agregar sin eliminar las existentes.'],
  ['estatico', '¿Cuál es la estructura correcta de una ruta estática?', ['ip router HOST DNS', 'ip route DESTINO MÁSCARA SIGUIENTE_SALTO', 'router static VLAN', 'network DESTINO area 0'], 1, 'ip route necesita el prefijo destino, su máscara y una salida/siguiente salto alcanzable.'],
  ['estatico', 'El ping llega al destino, pero no vuelve. ¿Qué revisarías?', ['Solo el hostname', 'El color del cable', 'La ruta de regreso y el gateway remoto', 'El nombre de la VLAN'], 2, 'La comunicación es bidireccional. La respuesta necesita un camino hacia la IP origen.'],
  ['rip', 'Una ruta RIP tiene métrica 16. ¿Qué significa?', ['Inalcanzable', 'La mejor ruta', '16 Mb/s', 'Área 16'], 0, 'RIP permite hasta 15 saltos alcanzables; 16 representa infinito.'],
  ['rip', '¿Para qué sirve no auto-summary en RIPv2?', ['Desactiva RIP', 'Borra las máscaras', 'Desactiva todos los resúmenes manuales', 'Desactiva el resumen automático classful'], 3, 'Evita el resumen automático en límites de redes mayores. RIPv2 transporta las máscaras de las subredes.'],
  ['ospf', '¿Cuál es el área backbone de OSPF?', ['Área 1', 'Área 0', 'La de mayor número', 'Cualquiera con RIP'], 1, 'El área 0 es el backbone. La afirmación “área 0 no backbone” de un apunte era una errata.'],
  ['ospf', '¿Cuál debe ser único entre los routers OSPF?', ['El process ID local', 'El número de área', 'El router ID', 'La máscara del enlace compartido'], 2, 'El router ID identifica al router. El process ID es local y puede coincidir o diferir entre equipos.'],
  ['eigrp', '¿Qué combina EIGRP con los valores K clásicos por defecto?', ['Ancho de banda mínimo y retardo acumulado', 'Solo saltos', 'Solo latencia de ping', 'Cantidad de VLAN'], 0, 'Su métrica compuesta usa ancho de banda y retardo con los valores K por defecto.'],
  ['eigrp', 'Para ser vecinos en EIGRP clásico, los routers necesitan…', ['Distinto AS', 'El mismo hostname', 'La misma IP', 'El mismo AS y parámetros compatibles'], 3, 'El número de AS debe coincidir, además de existir conectividad y compatibilidad de parámetros.'],
  ['dhcp', '¿Cuál es el orden de DORA?', ['Discover, Request, Offer, ACK', 'Discover, Offer, Request, ACK', 'DNS, Offer, Route, Access', 'ACK, Request, Offer, Discover'], 1, 'Descubrir, ofrecer, solicitar y confirmar. Es la secuencia típica de asignación inicial.'],
  ['dhcp', 'El servidor DHCP está en otra subred. ¿Qué suele hacer falta en el gateway del cliente?', ['Una MAC sticky', 'Borrar la VLAN', 'ip helper-address hacia el servidor', 'Desactivar el trunk'], 2, 'El relay reenvía solicitudes hacia el servidor remoto. También se necesitan rutas de ida y regreso.'],
  ['seguridad', '¿Cuándo guardas para conservar la MAC sticky aprendida?', ['Después de generar tráfico y verificar la MAC', 'Solo antes de conectar la PC', 'Nunca', 'Al borrar la VLAN'], 0, 'La MAC aparece en running-config al aprenderse. Guarda después para conservarla en startup-config.'],
  ['seguridad', 'El puerto está err-disabled por una violación. ¿Cuál es la recuperación de esta práctica?', ['Solo cambiar el DNS', 'Crear otra VLAN', 'Dejar al intruso y reiniciar siempre', 'Retirar al intruso, reconectar al autorizado y shutdown/no shutdown'], 3, 'Primero elimina la causa; luego reactiva y verifica. Si sigue la MAC no autorizada, puede caer otra vez.'],
].map(([topic, prompt, options, answer, explanation], index) => ({ id: index + 1, topic, prompt, options, answer, explanation }));

export const commands = [
  ['enable', 'Usuario >', 'Entra a EXEC privilegiado.', 'ios'],
  ['configure terminal', 'Privilegiado #', 'Entra a configuración global.', 'ios'],
  ['end', 'Configuración', 'Regresa a EXEC privilegiado.', 'ios'],
  ['write memory', 'Privilegiado #', 'Guarda running-config en startup-config.', 'ios'],
  ['show running-config', 'Privilegiado #', 'Muestra la configuración activa.', 'ios'],
  ['show startup-config', 'Privilegiado #', 'Muestra lo guardado para el arranque.', 'ios'],
  ['show ip interface brief', 'Privilegiado #', 'IP, estado físico y protocolo de interfaces.', 'interfaces'],
  ['show controllers serial0/0/0', 'Privilegiado #', 'Comprueba el extremo DCE/DTE de una serial.', 'interfaces'],
  ['ip address 192.168.1.1 255.255.255.0', '(config-if)#', 'Asigna IP a interfaz L3 o SVI; no a switchport L2.', 'interfaces'],
  ['no shutdown', '(config-if)#', 'Habilita administrativamente la interfaz.', 'interfaces'],
  ['vlan 101', '(config)#', 'Crea o selecciona la VLAN 101.', 'vlans'],
  ['name SISTEMAS', '(config-vlan)#', 'Asigna nombre a la VLAN seleccionada.', 'vlans'],
  ['switchport mode access', '(config-if)#', 'Fija modo access en el puerto.', 'vlans'],
  ['switchport access vlan 101', '(config-if)#', 'Asigna la VLAN de datos al puerto access.', 'vlans'],
  ['show vlan brief', 'Privilegiado #', 'VLANs, nombres y puertos access; no es el listado de trunks.', 'vlans'],
  ['show mac address-table', 'Privilegiado #', 'MAC aprendidas, VLAN y puerto asociado.', 'vlans'],
  ['switchport mode trunk', '(config-if)#', 'Configura un enlace troncal.', 'trunks'],
  ['switchport trunk allowed vlan add 101', '(config-if)#', 'Agrega 101 sin reemplazar la lista actual.', 'trunks'],
  ['show interfaces trunk', 'Privilegiado #', 'Trunks operativos, VLAN nativa y VLAN permitidas.', 'trunks'],
  ['interface vlan 100', '(config)#', 'Entra a la SVI de administración de la práctica.', 'trunks'],
  ['ip default-gateway 10.168.0.1', '(config)#', 'Gateway de administración de un switch que no enruta.', 'trunks'],
  ['ip routing', '(config)#', 'Habilita routing IPv4 en un switch multicapa compatible.', 'trunks'],
  ['ip route 192.168.4.0 255.255.255.0 209.168.130.66', '(config)#', 'Ruta estática del escenario R1 hacia la LAN remota.', 'estatico'],
  ['show ip route', 'Privilegiado #', 'Tabla de rutas: C, L, S, R, O, D…', 'estatico'],
  ['show ip protocols', 'Privilegiado #', 'Protocolos activos y redes configuradas.', 'rip'],
  ['router rip', '(config)#', 'Entra al proceso RIP; configura version 2 y sus networks.', 'rip'],
  ['no auto-summary', '(config-router)#', 'Desactiva el resumen automático en RIP/EIGRP clásico.', 'rip'],
  ['router ospf 1', '(config)#', 'Inicia/selecciona el proceso local OSPF 1.', 'ospf'],
  ['show ip ospf neighbor', 'Privilegiado #', 'Vecinos OSPF y estado de adyacencia.', 'ospf'],
  ['show ip ospf interface', 'Privilegiado #', 'Costo, área, tipo de red y temporizadores OSPF.', 'ospf'],
  ['show ip eigrp neighbors', 'Privilegiado #', 'Vecinos EIGRP.', 'eigrp'],
  ['ip dhcp excluded-address 10.168.101.1 10.168.101.10', '(config)#', 'Reserva IPs que DHCP no debe asignar.', 'dhcp'],
  ['ip dhcp pool SISTEMAS', '(config)#', 'Crea o edita el pool DHCP.', 'dhcp'],
  ['default-router 10.168.101.1', '(dhcp-config)#', 'Gateway entregado a los clientes del pool.', 'dhcp'],
  ['show ip dhcp binding', 'Privilegiado #', 'Concesiones de direcciones del servidor DHCP.', 'dhcp'],
  ['show ip dhcp pool', 'Privilegiado #', 'Estado y disponibilidad de los pools.', 'dhcp'],
  ['show port-security interface fa0/1', 'Privilegiado #', 'Estado de seguridad, máximo de MAC y violaciones.', 'seguridad'],
  ['show port-security address', 'Privilegiado #', 'Direcciones MAC seguras aprendidas/configuradas.', 'seguridad'],
  ['switchport port-security mac-address sticky', '(config-if)#', 'Aprende MAC seguras en running-config.', 'seguridad'],
  ['ping 10.168.101.1', 'EXEC o PC', 'Comprueba conectividad ICMP con el gateway de Sistemas.', 'interfaces'],
].map(([command, mode, description, topic]) => ({ command, mode, description, topic }));
